services:
  farmfarm-server:
    image: springdream0406/farmfarm-nest:latest
    ports:
      - 3000:3333
    environment:
      DB_TYPE: mysql
      DB_HOST: farmfarm-db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: farmfarm2024!
      DB_DATABASE: farmfarm
    depends_on:
      - farmfarm-db

  farmfarm-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: farmfarm
      MYSQL_ROOT_PASSWORD: farmfarm2024!
    ports:
      - 3001:3306
